### ISSUE TITLE
Add support for catch-all route

### ISSUE THREAD

**Issue by bperel** [matthiaaas/express-file-routing#17]
First of all, thank you for this package.

In Nuxt 3, there is support for [catch-all routes](https://v3.nuxtjs.org/guide/directory-structure/pages/#catch-all-route). This is useful when one wants to catch routes with a variable depth, for instance `/path/to/file` and `/path/to/a/deeply/nested/file` would be both captured by a file named `/path/to/[...path].js`.

Could express-file-routing have support for these catch-all routes?

**Comment by matthiaaas** [comment]
hey @bperel, thank you for the feature request.
I think a catch-all route makes a lot of sense for this package.
I'm familiar such routing behavior from Next.js.

Would you expect a [...catchall].ts route to also support the common method handlers `get`, `post` etc or just a single wildcard handler for all http methods?

**Comment by bperel** [comment]
Thanks for the quick answer :-) 

I would say that this catch-all route should support the command method handlers as any "normal" route would do, for the sake of consistency with the existing behavior with static and dynamic routes.

**Comment by matthiaaas** [comment]
Yes, I agree. Will come up with a feature implementation soon and keep you updated.

**Comment by RonaldBunk** [comment]
> hey @bperel, thank you for the feature request. I think a catch-all route makes a lot of sense for this package. I'm familiar such routing behavior from Next.js.
> 
> Would you expect a [...catchall].ts route to also support the common method handlers `get`, `post` etc or just a single wildcard handler for all http methods?

Wouldn't be quite effective (if possible) to use `[*].ts`, `[any].ts`, `[all].ts`?
How about allowing to custom placeholders in the configuration? Basically to do the above, but allow the end-user to do whatever they want.

**Comment by matthiaaas** [comment]
> Wouldn't be quite effective (if possible) to use `[*].ts`, `[any].ts`, `[all].ts`? How about allowing to custom placeholders in the configuration? Basically to do the above, but allow the end-user to do whatever they want.

What do you mean by placeholders? Currently, `[any].ts` would resolve to a dynamic route with a request parameter named _any_.

**Comment by RonaldBunk** [comment]
> > Wouldn't be quite effective (if possible) to use `[*].ts`, `[any].ts`, `[all].ts`? How about allowing to custom placeholders in the configuration? Basically to do the above, but allow the end-user to do whatever they want.
> 
> 
> 
> What do you mean by placeholders? Currently, `[any].ts` would resolve to a dynamic route with a request parameter named _any_.

That certain names will be replaced with predefined predicates such as "[any]" for "whatever".

**Comment by NotaRobot13** [comment]
@matthiaaas any update on this?

**Comment by matthiaaas** [comment]
Implemented under v2.1.0+. @bperel let me know if this meets your requirements.

**Comment by bperel** [comment]
Yes, thank you for implementing it :-)
