### ISSUE TITLE
Add support for error routes

### ISSUE THREAD

**Issue by RonaldBunk** [matthiaaas/express-file-routing#19]
Allowing to display said error pages based on a few predefined error states.

Example:
- Page not found -> `404.ts` / `not-found.ts`
- Error while processing the request -> `500.ts` / `server-error.ts`

Perhaps this is beyond the scope of this project, but perhaps there could be made a way to hook into such logic?

**Comment by matthiaaas** [comment]
hey @Azoraqua, thank you for filing an issue. Under the current implementation, you would have to add an error middleware/route handler after the router() invocation.
```ts
app.use(router()) // or createRouter(app)

// do whatever you want here
// like defining additional handlers
app.get("/foo", async () ...)

// actual error handling middleware
app.use(async (err, req, res, next) => {

})
```
I think that this behavior is desirable. It allows you to append as many `router()` instances to an app or even define additional native Express handlers as you want before declaring all error handling.

Also, I think that response error handling is something that should be logically separated from the actual routing. Unlike other file routing implementations in (frontend web) frameworks, this library does not try to force you to solely use file-based routing, but is supposed to be compatible with other routing strategies in a project that run in parallel.

But, I agree that for some projects, your suggestion is an absolutely valid and straight-forward approach. I'm just unsure if this should rather be outsourced to another plugin-like library that extends this package.

Let me know what you think.

**Comment by RonaldBunk** [comment]
I am fine with either option, optionally it could be a simple configuration option that handles it.
