### ISSUE TITLE
Please use require-main-filename package instead of direct require.main.filename

### ISSUE THREAD

**Issue by PaulMaly** [matthiaaas/express-file-routing#2]
Hi! In some environments, your module throws an error:

`TypeError: Cannot read property 'filename' of undefined`

Please, check this module: https://www.npmjs.com/package/require-main-filename

Seems, it can fix this problem.

**Comment by matthiaaas** [comment]
hey, thank you for your bug report. I will check that package out. In what environment did it throw that error?

**Comment by PaulMaly** [comment]
If I use `"type": "module"` in package.json. It happens because `module.parent` simply doesn't exist in Node ES Modules. NodeJS version 14 and upper.

**Comment by matthiaaas** [comment]
Unfortunately, I can't reproduce this by adding `"type": "module"` to a package.json. I'm not sure if this issue is rather connected to alternative node process managers.

Do you have an example project somewhere so I can do some further investigation? @PaulMaly

**Comment by derwo** [comment]
I have the same issue.
Worked fine until I switched to using ES Modules, now gives me the same error.

`TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.<anonymous> (.../node_modules/express-file-routing/dist/index.js:141:73)`

**Comment by matthiaaas** [comment]
Sorry for the error @derwo. Could you share your tech stack on the project or the whole codebase? I will implement a fix for these environments as described by @PaulMaly, but I need a testing setup for that purpose.
Thanks in advance!

**Comment by derwo** [comment]
I was trying to port an Express app (created with `express-generator`) from CommonJS to ESM.
You should be able to recreate the same environment with [express-generator](https://expressjs.com/en/starter/generator.html) and then adding `"type": "module"` to the package.json (probably will need to rename entry point and edit requires).
I'm using node `v16.14.0`.
Thanks to you!

**Comment by matthiaaas** [comment]
Published a patch in latest version `v2.0.1` (Commit: 0ca4b56), which is live on npm. It fixed the bug for me in my local testing environment.
Let me know if it works for you @derwo & thanks for the report.
