### ISSUE TITLE
Add support for preloading the library

### ISSUE THREAD

**Issue by RonaldBunk** [matthiaaas/express-file-routing#20]
If possible, it would be nice if it detects and registers the routes automatically.

NodeJS supports the `--require` (`-r` for short) flag, which automatically includes and executes said package. Perhaps something to do with this?

**Comment by matthiaaas** [comment]
hey @Azoraqua, I don't think I quite understand the feature you are requesting yet. Could you elaborate a bit on this one?

**Comment by RonaldBunk** [comment]
> hey @Azoraqua, I don't think I quite understand the feature you are requesting yet. Could you elaborate a bit on this one?

I meant to suggest, a way to detect routes in the filetree automatically. Similar to NextJS does it.

**Comment by matthiaaas** [comment]
@Azoraqua Still unsure if I get what you are requesting. Currently, somewhere in your codebase you habe to include the library by calling a function.
If not specified, routes source directory defaults to /routes (in Next.js it's /pages or /app).

The only difference is that Next.js provides a cli.

**Comment by RonaldBunk** [comment]
Alright, I'll accept it as is. Let's close this issue now.
