### ISSUE TITLE
Published version on npm console logs the routes and methods

### ISSUE THREAD

**Issue by jonluca** [matthiaaas/express-file-routing#21]
If you look at `https://www.npmjs.com/package/express-file-routing?activeTab=explore`, the router `console.log`s the route and method, even though this isn't in the source code. Could this be patched/fixed?

<img width="1420" alt="capture 2022-12-20 at 11 27 11 AM" src="https://user-images.githubusercontent.com/13029040/208645065-809772c7-4a2e-40c8-bdf8-db43b09ea2e3.png">

**Comment by dnorhoj** [comment]
This seems to have happened again

![image](https://user-images.githubusercontent.com/11206485/234125374-2a824f4c-49a9-4f70-b9e3-355d09cee59a.png)

**Comment by matthiaaas** [comment]
@dnorhoj fixed in latest release, build time linting was broken.
