### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module is not supported.

### ISSUE THREAD

**Issue by BluDood** [matthiaaas/express-file-routing#26]
Hello! I stumbled upon this package which perfectly fits what I'm looking for, however I'm getting an error while using it.
Here is my `index.js`:
```js
import express from 'express'
import { router } from 'express-file-routing'
import path from 'path'

const app = express()

app.use('/api', router({ directory: path.join(process.cwd(), 'routes') }))

app.listen(1337)
```
Here is my folder structure:
```
index.js
package.json
routes/
  users.js
  spaces.js
...
```
Finally, here is an example of a route file:
```js
export function get(req, res) {
  res.send('gm world')
}
```
Here is the full error:
```
<path_to_project>\node_modules\express-file-routing\dist\index.js:157
        const exports = require(path__default["default"].join(file.path, file.name));      
                        ^

Error [ERR_REQUIRE_ESM]: require() of ES Module <path_to_project>\routes\spaces.js from <path_to_project>\node_modules\express-file-routing\dist\index.js not supported.
Instead change the require of spaces.js in <path_to_project>\node_modules\express-file-routing\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at generateRoutes (<path_to_project>\node_modules\express-file-routing\dist\index.js:157:25)
    at createRouter (<path_to_project>\node_modules\express-file-routing\dist\index.js:182:20)
    at router (<path_to_project>\node_modules\express-file-routing\dist\index.js:211:12)
    at file:///<path_to_project>/index.js:7:17 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
```
It seems that the package is trying to `require()` the routes, however they are using ESM. Is this an incompatibility with plain JavaScript? I see that the examples in README.md are using TypeScript, is there a possibility this can be used with regular JavaScript and ESM as well?

**Comment by matthiaaas** [comment]
hey @BluDood, thank you for filing an issue. You are right, currently, ESM is not supported due to internal use of synchronous `require()` instead of async `await import()`.

There is a PR #18 wip that might be merged as part of v3 but also introduces a breaking change in the package's API.

```ts
// currently:
app.use(router())

// new draft (v3):
app.use(await router())
```

For now, you might take some inspiration from [this boilerplate](https://github.com/matthiaaas/clean-express-prisma). Alternatively, there is a buggy, unstable v3 beta on npm that can be installed via:

```
npm install express-file-routing@beta
```

But it probably needs some work to get it running. If you like to contribute and speed up the process, feel free to take a look at the v3 branch of this repo and try to get it stable. There shouldn't be too much work to do left.

**Comment by BluDood** [comment]
Thanks for the reply! I actually went back to commonjs for this project, as luckily none of the dependencies had any issues with it. It works great now, thanks!

**Comment by BluDood** [comment]
Hello again! I've decided to work on this a bit now, and got it working fine. However, I'm not that experienced with TypeScript so I'll have to look a bit more into that. I'll post the fork here tomorrow with the changes, and from there I can do a pull request if you'd like.
Sorry for any confusion I may have caused, I was just a bit burnt out yesterday and decided to go with the easiest option.

**Comment by matthiaaas** [comment]
hey @BluDood, thank you for putting in the work. Looking forward to it!

**Comment by BluDood** [comment]
Hello @matthiaaas!
I have now created a fork with the changes: [BluDood/express-file-routing@v3](https://github.com/BluDood/express-file-routing/tree/v3)
This fixes compatibility with ESM, however it seems to then break CJS compatibility because of the wildcard feature, since the "default" export of a CJS module looks like this:
```js
[Module: null prototype] {
  default: { get: [Function: get] },
  get: [Function: get]
}
```
And since [the check only checks if default is undefined](https://github.com/BluDood/express-file-routing/blob/v3/src/router.ts#L54), Express throws an error since it received an object instead of a function. I changed `exports.default.default` to `exports.default` because ES modules can provide the default export as a function, while also having other named exports.
Other changes I did:

- `package.json`: Changed `type` to `module`
- `rollup.config.js` Changed the output format to `es`
- `src/lib.ts`: Added `file://` to the start of import paths, since that's how import() works apparently. Tested working on Windows and Debian
- `src/router.ts`: Set the wildcard export to `export.default` instead of `export.default.default`
- `src/types.ts`: Removed the & type from Exports because it was causing an error. I don't know much TypeScript, but this is what I managed to get working

This now works perfectly fine with ESM enabled for vanilla JavaScript, however it does break compatibility with CJS. This can probably be fixed with some changes to the types I had to remove, but I have very limited TypeScript knowledge.

Let me know if I should make a pull request, or if I should change anything first!

**Comment by matthiaaas** [comment]
Thanks @BluDood, feel free to make a PR to push into the `v3` branch so we can discuss the changes over there.

**Comment by BluDood** [comment]
#27 created :)

**Comment by matthiaaas** [comment]
Merged it and fixed cjs compatibility. You can test the latest version with `npm install express-file-routing@beta`. Let me know if it works @BluDood. Will work on this now to ship v3 soon so feedback is appreciated!

**Comment by BluDood** [comment]
That's great! I'll be back in about an hour, then I'll test it both with CJS and ESM :)

**Comment by BluDood** [comment]
Hey @matthiaaas, I've tested it with both ESM and CJS and here are my results:

- CommonJS: It works fine, with one quirk that the "default" export for a wildcard route has to be `default.default` like so:

```js
module.exports = {
  default: async (req, res) => {
    if (req.method !== 'GET') return res.status(405)

    return res.json({ hello: 'world' })
  }
}
```

- ESM: 
I get this error (Windows):
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```
As the error says, it seems that ES modules imported with an absolute path must start with `file://`. I implemented this fix [here](https://github.com/matthiaaas/express-file-routing/commit/bd4c93436e93a7e3f02ee0412664fce56046b076#diff-e59662795ab51f95e1bf2a44d30dd0debbc194a499adffd1bb6a197bd188d4b5R61), however it seems you later removed it [here](https://github.com/matthiaaas/express-file-routing/commit/b3e6c4a66ac3470c9829d05d6f064fde0c0ae3bc#diff-e59662795ab51f95e1bf2a44d30dd0debbc194a499adffd1bb6a197bd188d4b5R61). I suppose it worked without the fix if you're on a different platform than Windows, however adding `file://` at the start still worked fine on Debian (WSL) for me, and also enables Windows support.

I hope we can fix this!

**Comment by matthiaaas** [comment]
What beta version are you on? The latest should be beta.4

**Comment by matthiaaas** [comment]
Also thanks. I will put file:// in front for ESM imports. The reason I removed it initially was that it breaks CJS require support, but prefixing conditionally for ESM only does the trick.

**Comment by matthiaaas** [comment]
Alright, so the latest beta version `beta.5` should cover all the fixes. Let me know if that works for you too. Thank you for the effort @BluDood.

**Comment by BluDood** [comment]
Thanks! I will try it as soon as I can, and reply back with the results :)

**Comment by BluDood** [comment]
After some testing, it works great now! Both CommonJS and ESM are compatible, and they both work as expected. Thanks for the help!

**Comment by matthiaaas** [comment]
Perfect, thank you for your efforts @BluDood. I might do some minor changes and then publish v3 as stable and let you know. Thanks!
