### ISSUE TITLE
tsc build error

### ISSUE THREAD

**Issue by migueldamota** [matthiaaas/express-file-routing#29]
I am getting an error when I try to build my app.

<img width="1799" alt="image" src="https://github.com/matthiaaas/express-file-routing/assets/55055484/fa492a04-6f14-4610-a7e3-2a77308e4fec">

I managed to fix this issue by adding `undefined` to the `MethodExports` type for any other string than the others.

<img width="311" alt="image" src="https://github.com/matthiaaas/express-file-routing/assets/55055484/fb478fb6-0c0c-48e9-a297-f4097effcdb9">

**Comment by migueldamota** [comment]
And with version 3, I am getting another build error:
<img width="1375" alt="image" src="https://github.com/matthiaaas/express-file-routing/assets/55055484/1d1727f9-3f78-46a8-9ec4-c58e6d629460">

**Comment by matthiaaas** [comment]
hey @migueldamota, thank you for filing this issue. Did you notice the change in the API and awaited the router?

```ts
app.use(await router())

// or

await createRouter(app)
```

**Comment by migueldamota** [comment]
@matthiaaas Yes, I am using await

**Comment by migueldamota** [comment]
I also tried it with [swc](swc.rs) and it works perfectly because there you have to mark your app as a module which I don't have before. So I may stay with swc.

**Comment by matthiaaas** [comment]
Can you try updating to the latest version v3.0.1? @migueldamota

**Comment by migueldamota** [comment]
@matthiaaas Yes, it works now! 🙌  Thank you!
