### ISSUE TITLE
Wrong README example

### ISSUE THREAD

**Issue by PaulMaly** [matthiaaas/express-file-routing#3]
Please, check this README line:

`If you export functions named one of get, post, put, delete those will get matched their corresponding http method.`

In javascript, we can't create a function named `delete`. In CommonJS system we can handle this point like this:

```javascript
module.exports = {
    delete: del,
};

async function del() {}
```

But examples based on ES modules.

**Comment by matthiaaas** [comment]
@PaulMaly Can you think of an ES-module-ish workaround for this?

Maybe just replacing/resolving `del` function exports with `delete` automatically?

**Comment by PaulMaly** [comment]
Actually, for ES exports I also have a workaround I forgot previously:

```javascript
async function del() {}

export { del as delete };
```

So, you have a choice just to improve the README to highlight this way or maybe support both variants: `delete` and `del` to be able to write less code:

```javascript
export async function del() {
   ...
}
```

I'm not sure you need my advice to choose the way to handle it. All I know is that we can't just create a function handler with a reserved name.

**Comment by matthiaaas** [comment]
Updated README in b666df4
