### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eykrehbein** [matthiaaas/express-file-routing#30]
Hi Matthias!

I really appreciate your work. Super interesting approach!
I was wondering what License the code is under, since the package.json states `MIT` but there is no clear LICENSE file. Clarifying this (whatever type of licence you choose) would make it easier for companies and individuals to know whether they can use it, redistribute it or contribute.

**Comment by matthiaaas** [comment]
hey @eykrehbein, thank you for addressing this. This project is now MIT-licensed as stated in the package.json with an corresponding LICENSE file.
