### ISSUE TITLE
[question] Is it possible to generate an OpenAPI specification of an Express app that uses express-file-routing

### ISSUE THREAD

**Issue by bperel** [matthiaaas/express-file-routing#31]
Thanks again for this nice library.

I would be interested in generating an OpenAPI specification of my Express application, for example using [swagger-autogen](https://github.com/davibaltar/swagger-autogen). I have run a few tests and it looks like express-file-routing's syntax is not recognized by swagger-autogen. Do you know if there are ways to generate such specification while using file-based routes?

**Comment by matthiaaas** [comment]
hey @bperel, what API did you use to register the router? I'm not sure how swagger generates the API doc, but it seems like that it supports express.Router.

I'd try using `app.use("/", await router())` since router() returns an express.Router instance.

**Comment by matthiaaas** [comment]
Alternatively, you could try using something like [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc) to generate Open API spec from.

**Comment by bperel** [comment]
Thank you for the suggestions. I did try to call `router()` like that (although without `await` as my test code is still using v2 of express-file-routing) but none of the routes got generated.


Here is [a diff showing what I mean](https://github.com/davibaltar/example-swagger-autogen-with-router/compare/main...bperel:example-swagger-autogen-with-router:main): in my fork, I converted the route declarations so that they use express-file-routing, and as you can see the swagger-output.json file misses all the routes (I added a screenshot as well).
As far as I saw in swagger-autogen's source code, it parses the route files in a very specific way, which I think is why it doesn't see the route files following express-file-routing conventions.

![missing-routes](https://github.com/matthiaaas/express-file-routing/assets/1484692/ac9738fe-4a9d-44ce-94de-186143d92a2f)

**Comment by matthiaaas** [comment]
I see, the library might not be able to support autogen.
But I saw people using swagger-jsdoc as a workaround, which would be my recommendation too.

**Comment by matthiaaas** [comment]
Closing this. Let me know if you need any other guidance @bperel.
