### ISSUE TITLE
jsx & tsx extension support

### ISSUE THREAD

**Issue by stalingino** [matthiaaas/express-file-routing#32]
Since bun.sh natively support jsx format, it would be nice to make use of the feature using this file based routing. Please include them in the allowed extensions.

**Comment by matthiaaas** [comment]
hey @stalingino, thank you for opening the issue. Is the use case for this to be able to declare JSX & render to HTML directly from within a route file?

Howsoever, I don't think including `.jsx` and `.tsx` will introduce any downsides, so I might add them in the next version.
