### ISSUE TITLE
BUG: Catchalls appear to be loaded prior to regular routes.

### ISSUE THREAD

**Issue by InfinityDevTech** [matthiaaas/express-file-routing#34]
## The title says it all.
So, when someone tries to serve a react app that is routed using browser routing (`/page/web`) kinda syntax.
If you implement a catchall in the root directory of your routes, it appears the catchall is loaded prior to regular routes, so regular routes don't get any recognition from express.

## Solution
Load catchalls in the root directory after all the other routes are completed.

**Comment by matthiaaas** [comment]
Thank you for raising an issue @InfinityDevTech.

Could you share how the react app is served in this scenario? Just a small Express file with the config and the created route files for reproducing the problem should be enough.

**Comment by matthiaaas** [comment]
hey @InfinityDevTech,

I just tried reproducing this using the following routing and any subsequent configuration of this:

```
├── app.js
├── routes
    ├── index.js
    ├── home.js
    ├── [...catchall].js
    └── page
        └── web.js
└── package.json
```

-  / → `/routes/index.js`
-  /home → `/routes/home.js`
-  /asdf → `/routes/[...catchall].js`
-  /page/web → `/routes/page/web.js`
-  /page/asdf → `/routes/[...catchall].js`

And for me it works just fine as I would expect it.

Could you share the version of this package you are on and a minimal set of routes that breaks it for you? Would love to fix this asap if we can confirm that there is an issue. Thank you!

**Comment by InfinityDevTech** [comment]
I completely forgot about this issue lol.

I was using a static express site and I ran 
`app.use(express.static(pathToApp))`

I think my problem was putting that before the router definition. But I'm not 100% sure.

I had the catchall redirect and serve that file too.

I fixed it, I'm just not 100% sure how.
