### ISSUE TITLE
Is it possible to ignore nested folders to support actions like testing

### ISSUE THREAD

**Issue by jackcrane** [matthiaaas/express-file-routing#39]
File routing tries to pull in all files in the workspace, including those in `tests` or `test` folders, and ending with `.test.js`. This will cause errors if testing libraries are pulled in during runtime code. It would be nice to be able to ignore all .test.js files

**Comment by matthiaaas** [comment]
Hi @jackcrane, thank you for raising an issue.
Only source files inside the specified routes directory are being used for route generation.

You can either move the tests folder outside of the routes directory or prefix them with an underscore to exclude them.
