### ISSUE TITLE
Please add few very useful features

### ISSUE THREAD

**Issue by PaulMaly** [matthiaaas/express-file-routing#4]
Hi!  I found almost the same package with few very important features. What do you think about adding the same features to this package?

More info: https://github.com/mathec-x/express-file-based/issues?q=is%3Aissue+is%3Aclosed

**Comment by matthiaaas** [comment]
Thank you for that report!

I will ask the dev to push his commits as a PR into this package. Unfortunately, he didn't give copyright notice in his package (which is obviously mostly copied and a clone of the code in this repo).

I like his changes, but I wished he'd have contributed to this repository.

**Comment by PaulMaly** [comment]
It would be the best variant. I was also surprised that the author of the alternative package didn't even try to contribute to this one.

**Comment by matthiaaas** [comment]
@mathec-x Would you please stop releasing the same package over and over again? https://github.com/mathec-x/express-next-api This is literally an 80% clone of this repo again.

**Comment by PaulMaly** [comment]
@matthiaaas maybe @mathec-x don't know what fork is?

**Comment by matthiaaas** [comment]
He does, I mean he opened a PR I merged recently.

**Comment by PaulMaly** [comment]
Yea, I saw that, but I mean if someone wants to develop oss project based on another one in own repo, he can just fork it. And it will be right way to do that.

**Comment by PaulMaly** [comment]
Btw, seems you can now close several issues with that PR, right? Could you please publish a new version to NPM, I would like to update my package and test these changes. Thanks!

**Comment by matthiaaas** [comment]
Just because it's open source doesn't mean you can do whatever you want with the codebase.
Often there's a license you need to follow. Otherwise you should ask for permission directly.

And also, a soft rule to open source is to respect ownership and appreciate other's work by not just cloning a repo and distributing it with minimal changes.
