### ISSUE TITLE
Prevent loading of all files

### ISSUE THREAD

**Issue by jackcrane** [matthiaaas/express-file-routing#40]
Hi;

Would it be somehow possible to prevent this from loading every file? The fact that it does this prevents codecoverage reports to be accurate. Do you have any suggestions on getting accurate codecoverage reports for testing with this package? Thanks

**Comment by matthiaaas** [comment]
Hi @jackcrane, what do you mean by loading every file?

**Comment by jackcrane** [comment]
Im not necessarily sure, but all I can say is that code coverage doesn't work; everything is very over-inflated and is a useless metric unless this is fixed.

**Comment by matthiaaas** [comment]
Without further details including a repro and more concise description of the issue, I'm afraid I won't be able to support.

**Comment by jackcrane** [comment]
Running `yarn test --coverage --ui` on this repository would be a repro. As for more of a description, i dont know what else I can suggest.

https://github.com/jackcrane/slu-open-project

**Comment by matthiaaas** [comment]
I would not recommend colocating your tests with your routes inside the `/routes` directory.
