### ISSUE TITLE
Add support Windows

### ISSUE THREAD

**Issue by Rysakov1986** [matthiaaas/express-file-routing#5]
Hello! Okay, the analogue was removed where I asked to add my ideas, then you can add them here? ))

Please replace/add from ":id.ts" to "$id.ts"

Thanks!

**Comment by matthiaaas** [comment]
What do you think of a Next.js like workaround with wrapping `[]` e.g. `[id].ts`?

**Comment by Rysakov1986** [comment]
It`s good, i thought to offer this option)

**Comment by matthiaaas** [comment]
Alright, I'll wait for @mathec-x Pull Request, which will include all the changes you already raised in his repo so I don't need to reimplement those solutions. So sorry for this inconvenience, hopefully we'll see a PR shortly!

**Comment by Rysakov1986** [comment]
Is @mathec-x ready to cooperate, did he say anything about it?

**Comment by matthiaaas** [comment]
Yes, I reached out to him already and he said he's preparing a PR at the moment. Hopefully we'll see his changes merged into this repo by tomorrow.

**Comment by PaulMaly** [comment]
@matthiaaas I hope that @mathec-x will be added as a core team member of this repo (if he wants of course)? I believe it will be fair and help boost maintainability of this nice project.

**Comment by Rysakov1986** [comment]
@PaulMaly How are your hopes? )))

**Comment by matthiaaas** [comment]
I would be willing to make him a core contributor, but first of all he needs to respect some fundamental open source fairplay rules. He again released [another copy](https://github.com/mathec-x/express-next-api) of this package on his own GitHub & NPM without any credit or need for doing so.
