### ISSUE TITLE
Add filter/exclude for routes

### ISSUE THREAD

**Issue by Rysakov1986** [matthiaaas/express-file-routing#6]
Hello! Add filter/exclude routes if name start with "_". ex: "_index.ts"

Thanks!

**Comment by Rysakov1986** [comment]
Why was Issue closed? It's a very good idea to split the route into parts. For example, a validation schema in another file like _schema.js, _middlewares.js, etc.

**Comment by matthiaaas** [comment]
Because it's now implemented. Files/Folders starting with underscores are hidden.
