### ISSUE TITLE
Add priority for routes

### ISSUE THREAD

**Issue by Rysakov1986** [matthiaaas/express-file-routing#7]
Hello! Please add priority for routes (aka https://github.com/jesseditson/fs-router)
```php
// all routes are sorted by this property - the higher numbers are matched first.
// kind of like a z-index for your routes.
// note that equal priority will just sort based on the fs in the case of a collision, which is not guaranteed order on OSX/Linux
module.exports.priority = -1
```
Thanks!

**Comment by matthiaaas** [comment]
Just being curious, do you have am example codebase where there's a use case for this? Would love to see a demo. Like in Next.js there's no such feature and I never missed it to be honest.

**Comment by Rysakov1986** [comment]
This is necessary when your route layers come with dynamics and it is not clear when [car].js and car.js will respond

**Comment by matthiaaas** [comment]
Like in this case?

```
├── routes
    ├── [car].js
    └── car.js
```

No magic happening here, `car.js` will be higher priority by ExpressJS's native design https://gabrieleromanato.name/order-of-routes-when-using-parameters-in-expressjs
So I don't really see a need for this code feature (although it's now already merged into the codebase).

**Comment by PaulMaly** [comment]
@matthiaaas actually, it won't be a higher priority. Please, take a look at the blog post you provided a little more attentive:

> However, the above code doesn't work as intended because a parametric path inserted just before a literal one takes the precedence over the literal one.

> Bear in mind that in ExpressJS there's no built-in way to declare our routes as a list ordered by priority.

So, @Rysakov1986 meant that file systems in the different OS are able to give you surprises with sorting of the list of the files after you read it. So, an example from a blog post can be written like:

```bash
├── routes
    ├── [post].js
    └── page.js
    └── index.js
```

and your code will define something like:

 ```javascript
app.get('/:post', handlerPost);
app.get('/page', handlerPage);
app.get('/', handlerIndex);
 ```

and in this case `/page` path will be matched to the handler from `[post].js` file.

**Comment by matthiaaas** [comment]
Ah I see, I'm absolutely wrong on this. But wouldn't it be much more elegant to build in that priority feature into this package as I initially thought Express would do it already?
I don't like that export priority syntax so maybe this would be a much cleaner solution?

**Comment by PaulMaly** [comment]
Indeed, but to solve this issue in a more elegant way you'll need to adopt additional route matching to this package. Right now, this package just utilizes Express routing and leaves all these questions to it. To become smarter this package will need to do a lot more than now.

Please, take a look at how SvelteKit is fallthrough routes for the most similar case: https://kit.svelte.dev/docs#routing-advanced-fallthrough-routes

It doesn't use files list ordering but decides which route is the best match and even tries to call this route and go to the next match if it fails.

So, before defining a router in Express this package should sort an array of routes by matching priority using `path-to-regexp` directly. 

But I'm not sure it's a good idea. The current solution is nasty but it's simple, cheap, and gives full control if needed. Also, we remain exactly in the Express paradigm without any additional, not explicit, routing logic.

**Comment by matthiaaas** [comment]
I think ordering based on a sum of a depth and specifity metric should work fine. This rule would sort the following file tree 

```
├── routes
    ├── index.js
    └── posts
        ├── [id]
            ├── details.js
            └── index.js
        ├── index.js
        └── test.js
```

strictly into

```
/
/posts
/posts/test
/posts/:id
/posts/:id/details
```

After that maybe some alphabetic ordering needs to be done so there are no differences between different platforms.

**Comment by matthiaaas** [comment]
The method described above is now live on NPM.
