### ISSUE TITLE
Dynamic params for folder

### ISSUE THREAD

**Issue by Rysakov1986** [matthiaaas/express-file-routing#8]
Hello! Please add dynamic params for folder.

```php
├── app.ts
├── routes
    ├── index.ts
    ├── :posts // dynamic params
        ├── index.ts
        └── :id.ts
    └── users.ts
└── package.json
```
Thanks!

**Comment by matthiaaas** [comment]
hey @Rysakov1986, isn't this supported already? If not, feel free to reopen the issue. Maybe there's a note missing in the docs? What do you think?

**Comment by Rysakov1986** [comment]
I think I can answer this question when, after adding Windows support))
